### ISSUE TITLE
fix ct-exposer.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by darkcracker** [chris408/ct-exposer#10]
ct-exposer.py:32: SyntaxWarning: "is not" with a literal. Did you mean "!="? get this when trying enumerate .

**Comment by chris408** [comment]
It looks like this is something new from Python 3.8: https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/ I'll make a change in the future once I find a good workaround for the query issues.

**Comment by jepunband** [comment]
hi i got the same issue ...

**Comment by jeretc** [comment]
modify "is not" to "!=" in the ct-exposer.py file to like this, the text that is in bold. Execute the command again and you will not see the error. The problem now is the https://www.entrust.com/ct-search/ , the api, no results. Probably the service is down.
 pool = Pool(15)
    greenlets = [pool.spawn(resolve, domain) for domain in domains]
    pool.join(timeout = 1)
    for greenlet in greenlets:
        result=greenlet.value
        if (result):
            for ip in result.values():
                if ip **!=** 'none':
                    domainsFound.update(result)
                else:
                    domainsNotFound.update(result)

**Comment by ignisc4t** [comment]
removed warning, no result given, I think the service is down.
edit:
checking `https://ctsearch.entrust.com/api/v1/certificates...` forbidden access

but can access `https://www.entrust.com/ct-search/`

**Comment by chris408** [comment]
This is now fixed. Thanks for bringing this up.
