### ISSUE TITLE
no module named gevent

### ISSUE THREAD

**Issue by morzen** [chris408/ct-exposer#13]
i followed the installation procedure but this happenned

![image](https://user-images.githubusercontent.com/32000608/105481634-3c877d80-5c9f-11eb-97cf-e57f29846d30.png)

**Comment by obsti8383** [comment]
have you tried without "sudo"?

**Comment by morzen** [comment]
yea by doing python3 ct-exposer -d hackthebox.eu it work although i would sugest a little error message or something other wise it work fine many thanks
