### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JK-Love** [chris408/ct-exposer#14]
![image](https://user-images.githubusercontent.com/63699609/112406436-205f9580-8d4f-11eb-87a0-cab1974be1cc.png)

**Comment by chris408** [comment]
Hello, can you share what version/distribution of OS you are on and what version of python this is? I want to try to replicate this error.

**Comment by chris408** [comment]
Closing for now, feel free to reopen or create a new issue if you're still seeing the same problem.
