### ISSUE TITLE
Error: The server did not respond with a valid json response 

### ISSUE THREAD

**Issue by brigxt0** [chris408/ct-exposer#15]
Hi, im getting the below error on all domains l try to scan the python version is 3.10.4 and the Os is Termux on armv8l

 python ct-exposer.py -d google.com
[+]: Downloading domain list from crt.sh
[!]: The server did not respond with valid json.

 @localhost  ~clones/ct-exposer  python --version
Python 3.10.4
 @localhost  ~clones/ct-exposer  uname -a
Linux localhost 4.9.190-perf-g586dd41 #1 SMP PREEMPT Tue Feb 23 21:02:12 CST 2021 armv8l Android`

l have the following packages installed:

- aiodns==3.0.0
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
autopep8==1.6.0
black==22.3.0
bleach==4.1.0
build==0.7.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
click==8.0.3
click-plugins==1.1.1
colorama==0.4.4
commonmark==0.9.1
cryptography==2.8
decorator==5.1.1
docopt==0.6.2
docutils==0.18.1
frozenlist==1.3.0
gevent==21.12.0
greenlet==1.1.2
h2==4.1.0
hostchk==1.1.6
hpack==4.0.0
httpmethods==1.1.0
hyperframe==6.0.1
idna==3.3
importlib-metadata==4.11.3
ipcalc==1.99.0
iptools==0.7.0
jeepney==0.7.1
keyring==23.5.0
memory-profiler==0.60.0
multidict==6.0.2
mypy-extensions==0.4.3
netaddr==0.8.0
packaging==21.3
pathspec==0.9.0
pep517==0.12.0
pipreqs==0.4.11
pkginfo==1.8.2
platformdirs==2.5.1
psutil==5.9.0
pycares==4.1.2
pycodestyle==2.8.0
pycparser==2.21
pycryptodome==3.11.0
pyfiglet==0.8.post1
Pygments==2.10.0
pyparsing==3.0.7
pyte==0.8.0
readme-renderer==34.0
requests==2.26.0
requests-futures==1.0.0
requests-toolbelt==0.9.1
restructuredtext-lint==1.4.0
rfc3986==2.0.0
rich==12.0.1
SecretStorage==3.3.1
shodan==1.25.0
six==1.16.0
termcolor==1.1.0
thefuck==3.32
toml==0.10.2
tomli==2.0.1
tqdm==4.62.3
twine==4.0.0
urllib3==1.26.7
versioneer==0.22
wcwidth==0.2.5
webchk==1.0.4
webencodings==0.5.1
XlsxWriter==3.0.2
yarg==0.1.9
yarl==1.7.2
zipp==3.7.0
zope.event==4.5.0
zope.interface==5.4.0

**Comment by chris408** [comment]
Hi @brigxt0, I made change a moment ago that should resolve this, as it works again after some testing. Let me know if you see any new issues. Thanks.
