### ISSUE TITLE
Avoid potential dependency conflicts between ct-exposer and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [chris408/ct-exposer#8]
Hi, as shown in the following full dependency graph of  **_ct-exposer_**, **_ct-exposer_** requires _**urllib3**_ (the latest version)， while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint  (_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of **_urllib3_**.

### Dependency tree--------
```
ct-exposer(version range:)
| +-gevent(version range:)
| +-greenlet(version range:)
| +-requests(version range:)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency urllib3, and use the library urllib3 transitively introduced by requests.

Personally, I prefer solution 2.
What's your opinion?
@chris408 May I pull a request to solve this issue?

**Comment by chris408** [comment]
Thanks for bringing this up. I had added urllib3 in the past to try to avoid some error messages from requests. I removed it a moment ago.

Thanks!
