### ISSUE TITLE
every url I enter gives the following:

### ISSUE THREAD

**Issue by Brumbpo-Tungus** [chris408/ct-exposer#9]
Hey,

[+]: Downloading domain list...
[+]: Download of domain list complete.
[+]: Parsed 0 domain(s) from list.

[+]: Domains found:

[+]: Domains with no DNS record:

No matter what one I use

**Comment by domainController** [comment]
same here. tried under a virtualenv same result: involving /home/kami/.cache/pip/http as main suspect. Tried a clean AWS Linux instance running python 3.7 : Got this below error message while running pip3 install -r requirements.txt

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3ptaqx5s/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dh7y5e9u-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3ptaqx5s/gevent/

gevent is a networking library. ct-exposer not guilty. let's take a break.

**Comment by jstjep00** [comment]
> gevent is a networking library. ct-exposer not guilty. let's take a break.

Even after installing the specific older versions of gevent, greenlet and requests from the requirements.txt it still gives the same error. Could it be something else?

EDIT: Seems like Host ctsearch.entrust.com from function collectResponse has a malfunction on the search service as it reports "Error contacting search service" when domain is entered manually on their site. Some other service should be found.

**Comment by tares003** [comment]
guys I have traced the issued, it's not  due to gevernet!  seems to be due to Entrust server is under maintenance see website https://www.entrust.com/ct-search/ for latest updates.  

I do recommend to update script to google https://transparencyreport.google.com, API is exposed through https://transparencyreport.google.com/transparencyreport/api/v3/httpsreport/ct/certsearch?include_subdomains=true&domain=google.com

**Comment by tares003** [comment]
I have updated the script, added support for https://transparencyreport.google.com:
see my fork:  https://github.com/tares003/ct-exposer/. 

hope @chris408 could merge it.

**Comment by chris408** [comment]
@tares003 thanks for working on that. Google would likely be a more reliable source. However when I tested a few domains that I'm familiar with I noticed a lot of results were missing. I'll have to look into this more to try and find a solution.

**Comment by tares003** [comment]
@chris408 I am not sure how the other API works/worked (still compatible with other API), on google's API I've limited only the 5 most recent updates of from logs, I have removed the restrictions so it should grab all the domains.

**Comment by ignisc4t** [comment]
> @chris408 I am not sure how the other API works/worked (still compatible with other API), on google's API I've limited only the 5 most recent updates of from logs, I have removed the restrictions so it should grab all the domains.

so, it can grabbing whole domain then ?
I'm just curious if google will block my ip (again) with this api.

**Comment by tares003** [comment]
> > @chris408 I am not sure how the other API works/worked (still compatible with other API), on google's API I've limited only the 5 most recent updates of from logs, I have removed the restrictions so it should grab all the domains.
> 
> so, it can grabbing whole domain then ?
> I'm just curious if google will block my ip (again) with this api.

yes, all the domains, including the redundant domains.

**Comment by chris408** [comment]
This should be fixed in my latest update. The old service we used seems to be broken with no sign it will come back any time soon. I moved to crt.sh and so far it has been working well. Let me know if you find any new issues.
